import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

export type SupportedLang = 'en' | 'hi';

type Dictionary = Record<string, string>;

type TranslationBundle = Record<SupportedLang, Dictionary>;

const translations: TranslationBundle = {
  en: {
    appTitle: 'AgroAI Platform',
    modalTitleLogin: 'Sign In',
    modalTitleRegister: 'Create Account',
    modalTitleForgot: 'Forgot Password',
    modalTitleReset: 'Reset Password',
    home: 'Home',
    dashboard: 'Dashboard',
    weather: 'Weather',
    yieldPrediction: 'Yield Prediction',
    recommendation: 'Crop Recommendation',
    optimization: 'Resource Optimization',
    risk: 'Risk Assessment',
    simulator: 'What-If Simulator',
    explainable: 'Explainable AI',
    login: 'Login',
    signIn: 'Sign In',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetPassword: 'Reset Password',
    confirmPassword: 'Confirm Password',
    confirmNewPassword: 'Confirm New Password',
    newPassword: 'New Password',
    name: 'Name',
    aadhar: 'Aadhar Card Number',
    languageToggle: 'हिंदी / English',
    heroTitle: 'Smart Agriculture Solution',
    heroSubtitle: 'Make data-driven decisions with AI-driven insights.',
    goToDashboard: 'Go to Dashboard',
    landingLogin: 'Login',
    landingRegister: 'Register',
    forgotInstructions: 'Please enter your email to receive a password reset link.',
    registerLink: 'Register',
    loginLink: 'Login',
    alreadyAccount: 'Already have an account? Login',
    noAccount: "Don't have an account? Register",
    submit: 'Submit',
    successRegistration: 'Registration successful! Please login.',
    successReset: 'Password reset successful! Please login.',
    resetLinkSent: 'Reset link sent! Check your inbox.',
    invalidEmail: 'Please enter a valid email address.',
    aadharInvalid: 'Aadhar number must be 12 digits.',
    passwordMismatch: 'Passwords do not match.',
    sendLinkNote: 'We will send a reset link to your email.',
    navbarTitle: 'AgroAI Platform',
    headerSubtitle: 'AI-Powered Crop Intelligence Platform',
    close: 'Close',
    // Dashboard
    welcomeDashboard: 'AgroAI Platform Dashboard',
    dashboardSubtitle: 'AI-Powered Crop Yield Prediction & Optimization Platform',
    welcomeBack: 'Welcome back! Here\'s your farming intelligence overview.',
    totalPredictions: 'Total Predictions',
    avgYield: 'Avg Yield',
    successRate: 'Success Rate',
    activeFarmers: 'Active Farmers',
    kg: 'kg',
    yieldTrend: 'Yield Trend',
    month: 'Month',
    cropDistribution: 'Crop Distribution',
    riskAnalysis: 'Risk Analysis',
    riskLevel: 'Risk Level',
    count: 'Count',
    recentPredictions: 'Recent Predictions',
    crop: 'Crop',
    predictedYield: 'Predicted Yield',
    date: 'Date',
    riskBadge: 'Risk',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    predictYield: 'Predict Yield',
    yieldPredictionDesc: 'Get AI-powered crop yield predictions based on your field conditions',
    startPrediction: 'Start Prediction',
    cropRecommendationTitle: 'Crop Recommendation',
    recommendationsDesc: 'Find the best crops for your soil and climate conditions',
    getRecommendations: 'Get Recommendations',
    weatherForecast: 'Weather Forecast',
    // Yield Prediction
    aiCropYield: 'AI Crop Yield Prediction',
    yieldPredictionDesc2: 'Predict crop yield and assess cultivation risk using machine learning',
    enterFieldParameters: 'Enter Field Parameters',
    selectCrop: 'Select Crop',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    soilType: 'Soil Type',
    loam: 'Loam',
    sandy: 'Sandy',
    silty: 'Silty',
    peaty: 'Peaty',
    chalky: 'Chalky',
    soilColor: 'Soil Color',
    darkBrown: 'Dark Brown/Black',
    red: 'Red',
    yellow: 'Yellow',
    lightBrown: 'Light Brown',
    rainfall: 'Rainfall (mm)',
    annual: 'Annual',
    temperature: 'Temperature (°C)',
    average: 'Average',
    predictButton: 'Predict Yield',
    phEstimated: 'Soil pH (Estimated)',
    basedOn: 'Based on soil type, color, and waterlogging',
    contributingFactors: 'Contributing Factors:',
    soilHealth: 'Soil Health',
    weatherSuitability: 'Weather Suitability',
    nutrientBalance: 'Nutrient Balance',
    predictionResult: 'Prediction Result',
    predictedYieldLabel: 'Predicted Yield',
    riskLevelLabel: 'Risk Level',
    lowRisk: 'Low Risk - Good conditions',
    mediumRisk: 'Medium Risk - Monitor closely',
    highRisk: 'High Risk - Take precautions',
    // CropRecommendation
    cropRecommendations: 'Crop Recommendations',
    recommendMsg: 'Based on your soil and climate conditions',
    noRecommendations: 'Enter field parameters to get recommendations',
    match: 'Match',
    expectedYield: 'Expected Yield',
    firstChoice: 'Recommended First Choice',
    aiRecommendationTip: 'AI Recommendation Tip',
    tipText: 'These recommendations are based on machine learning analysis of your soil nutrients, pH levels, and climate conditions. The top choice offers the best yield potential for your specific conditions.',
    // Weather
    temperatureGuide: 'Temperature Guide',
    ideal: 'Ideal for most crops. Best time for planting and field operations.',
    increase: 'Increase irrigation. Monitor crops for heat stress.',
    critical: 'Critical! Provide shade, increase watering frequency.',
    rainfallExpected: 'Rainfall Expected',
    rainfallMsg: 'Moderate to heavy rainfall forecasted in 2-3 days. Ensure proper field drainage. Complete fertilizer application before rains. Harvest mature crops if ready.',
    favorableConditions: 'Favorable Conditions',
    favorableMsg: 'Perfect weather for farming operations! Temperature and humidity are ideal. Good time for planting, spraying, and general field work.',
    // Additional form and UI strings
    soilLoam: 'Loam',
    soilSandy: 'Sandy',
    soilSilty: 'Silty',
    soilPeaty: 'Peaty',
    soilChalky: 'Chalky',
    soilDarkBrown: 'Dark Brown/Black',
    soilRed: 'Red',
    soilYellow: 'Yellow',
    soilLightBrown: 'Light Brown',
    riskAssessment: 'Risk Assessment',
    assessRisk: 'Assess Cultivation Risk',
    riskFactors: 'Risk Factors',
    riskFactorWeather: 'Weather Risk',
    riskFactorSoil: 'Soil Risk',
    riskFactorDisease: 'Disease Risk',
    overall: 'Overall',
    trendAnalysis: 'Risk Trend Analysis',
    fertilizerTitle: 'Resource Optimization',
    optimizeResources: 'Optimize Your Fertilizer & Irrigation',
    currentUsage: 'Current Usage',
    optimizedUsage: 'Optimized Usage',
    savings: 'Potential Savings',
    nitrogenLabel: 'Nitrogen Usage',
    phosphorusLabel: 'Phosphorus Usage',
    potassiumLabel: 'Potassium Usage',
    irrigationWater: 'Irrigation Water',
    costPerUnit: 'Cost Per Unit',
    estimatedCost: 'Estimated Cost',
    optimizationReport: 'Optimization Report',
    scenarioSimulator: 'What-If Scenario Simulator',
    simulateChanges: 'Simulate Different Field Conditions',
    scenario: 'Scenario',
    baseline: 'Baseline',
    recommendedChange: 'Recommended Change',
    warning: 'Warning',
    minorImpact: 'Minor Impact',
    yieldComparison: 'Yield Comparison',
    factorComparison: 'Factor Comparison',
    simulate: 'Simulate',
    explainableAI: 'Explainable AI',
    understandFactors: 'Understand What Factors Influence Your Yield',
    featureImportance: 'Feature Importance',
    affectsYield: 'Affects Your Yield',
    topFactors: 'Top Factors',
    explanation: 'AI Explanation',
    howItWorks: 'How It Works',
    analyze: 'Analyze',
    predict: 'Predict',
    reset: 'Reset',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View'
  },
  hi: {
    appTitle: 'एग्रोएआई प्लेटफ़ॉर्म',
    modalTitleLogin: 'साइन इन',
    modalTitleRegister: 'खाता बनाएँ',
    modalTitleForgot: 'पासवर्ड भूल गए',
    modalTitleReset: 'पासवर्ड रीसेट',
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    weather: 'मौसम',
    yieldPrediction: 'उत्पादन पूर्वानुमान',
    recommendation: 'फसल अनुशंसा',
    optimization: 'संसाधन अनुकूलन',
    risk: 'जोखिम आकलन',
    simulator: 'व्हाट-इफ़ सिम्युलेटर',
    explainable: 'समझाने योग्य एआई',
    login: 'लॉगिन',
    signIn: 'साइन इन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    sendResetLink: 'रीसेट लिंक भेजें',
    backToLogin: 'लॉगिन पर वापस जाएं',
    resetPassword: 'पासवर्ड रीसेट',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    confirmNewPassword: 'नया पासवर्ड पुष्टि करें',
    newPassword: 'नया पासवर्ड',
    name: 'नाम',
    aadhar: 'आधार कार्ड नंबर',
    languageToggle: 'हिंदी / English',
    heroTitle: 'स्मार्ट कृषि समाधान',
    heroSubtitle: 'एआई से मिली अंतर्दृष्टि के साथ डेटा-आधारित निर्णय लें।',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    landingLogin: 'लॉगिन',
    landingRegister: 'पंजीकरण',
    forgotInstructions: 'पासवर्ड रीसेट लिंक प्राप्त करने के लिए कृपया अपना ईमेल दर्ज करें।',
    registerLink: 'पंजीकरण',
    loginLink: 'लॉगिन',
    alreadyAccount: 'पहले से खाता है? लॉगिन करें',
    noAccount: 'खाता नहीं है? पंजीकरण करें',
    submit: 'सबमिट',
    successRegistration: 'पंजीकरण सफल! कृपया लॉगिन करें।',
    successReset: 'पासवर्ड रीसेट सफल! कृपया लॉगिन करें।',
    resetLinkSent: 'रीसेट लिंक भेज दिया गया! अपना ईमेल देखें।',
    invalidEmail: 'कृपया वैध ईमेल दर्ज करें।',
    aadharInvalid: 'आधार नंबर 12 अंकों का होना चाहिए।',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते।',
    sendLinkNote: 'हम आपके ईमेल पर रीसेट लिंक भेजेंगे।',
    navbarTitle: 'एग्रोएआई प्लेटफ़ॉर्म',
    headerSubtitle: 'एआई संचालित फसल इंटेलिजेंस प्लेटफ़ॉर्म',
    close: 'बंद करें',
    // Dashboard
    welcomeDashboard: 'एग्रोएआई प्लेटफ़ॉर्म डैशबोर्ड',
    dashboardSubtitle: 'एआई-संचालित फसल उत्पादन पूर्वानुमान और अनुकूलन प्लेटफ़ॉर्म',
    welcomeBack: 'आपका स्वागत है! यहाँ आपके कृषि बुद्धिमत्ता अवलोकन दिए गए हैं।',
    totalPredictions: 'कुल पूर्वानुमान',
    avgYield: 'औसत पैदावार',
    successRate: 'सफलता दर',
    activeFarmers: 'सक्रिय किसान',
    kg: 'किग्रा',
    yieldTrend: 'उत्पादन प्रवृत्ति',
    month: 'महीना',
    cropDistribution: 'फसल वितरण',
    riskAnalysis: 'जोखिम विश्लेषण',
    riskLevel: 'जोखिम स्तर',
    count: 'गणना',
    recentPredictions: 'हाल के पूर्वानुमान',
    crop: 'फसल',
    predictedYield: 'अनुमानित पैदावार',
    date: 'तारीख',
    riskBadge: 'जोखिम',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    predictYield: 'पैदावार की भविष्यवाणी करें',
    yieldPredictionDesc: 'अपनी खेत की स्थितियों के आधार पर एआई-संचालित फसल पैदावार पूर्वानुमान प्राप्त करें',
    startPrediction: 'भविष्यवाणी शुरू करें',
    cropRecommendationTitle: 'फसल अनुशंसा',
    recommendationsDesc: 'अपनी मिट्टी और जलवायु परिस्थितियों के लिए सर्वोत्तम फसलें खोजें',
    getRecommendations: 'सिफारिशें प्राप्त करें',
    weatherForecast: 'मौसम पूर्वानुमान',
    // Yield Prediction
    aiCropYield: 'एआई फसल पैदावार पूर्वानुमान',
    yieldPredictionDesc2: 'मशीन लर्निंग का उपयोग करके फसल पैदावार की भविष्यवाणी करें और खेती के जोखिम का मूल्यांकन करें',
    enterFieldParameters: 'खेत के पैरामीटर दर्ज करें',
    selectCrop: 'फसल चुनें',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फॉस्फोरस (P)',
    potassium: 'पोटेशियम (K)',
    soilType: 'मिट्टी का प्रकार',
    loam: 'दोमट',
    sandy: 'बलुई',
    silty: 'गाद वाली',
    peaty: 'पीट वाली',
    chalky: 'चॉकी',
    soilColor: 'मिट्टी का रंग',
    darkBrown: 'गहरा भूरा/काला',
    red: 'लाल',
    yellow: 'पीला',
    lightBrown: 'हल्का भूरा',
    rainfall: 'वर्षा (मिमी)',
    annual: 'वार्षिक',
    temperature: 'तापमान (°C)',
    average: 'औसत',
    predictButton: 'पैदावार की भविष्यवाणी करें',
    phEstimated: 'मिट्टी का पीएच (अनुमानित)',
    basedOn: 'मिट्टी के प्रकार, रंग और जलभराव के आधार पर',
    contributingFactors: 'योगदान देने वाले कारक:',
    soilHealth: 'मिट्टी स्वास्थ्य',
    weatherSuitability: 'मौसम की उपयुक्तता',
    nutrientBalance: 'पोषक तत्वों का संतुलन',
    predictionResult: 'भविष्यवाणी परिणाम',
    predictedYieldLabel: 'अनुमानित पैदावार',
    riskLevelLabel: 'जोखिम स्तर',
    lowRisk: 'कम जोखिम - अच्छी स्थितियाँ',
    mediumRisk: 'मध्यम जोखिम - बारीकी से निगरानी करें',
    highRisk: 'उच्च जोखिम - सावधानी बरतें',
    // CropRecommendation
    cropRecommendations: 'फसल अनुशंसाएं',
    recommendMsg: 'आपकी मिट्टी और जलवायु परिस्थितियों के आधार पर',
    noRecommendations: 'सिफारिशें प्राप्त करने के लिए खेत के पैरामीटर दर्ज करें',
    match: 'मैच',
    expectedYield: 'अपेक्षित पैदावार',
    firstChoice: 'अनुशंसित पहली पसंद',
    aiRecommendationTip: 'एआई अनुशंसा सुझाव',
    tipText: 'ये सिफारिशें आपकी मिट्टी के पोषक तत्वों, पीएच स्तर और जलवायु परिस्थितियों के मशीन लर्निंग विश्लेषण पर आधारित हैं। शीर्ष पसंद आपकी विशिष्ट परिस्थितियों में सर्वोत्तम उपज क्षमता प्रदान करती है।',
    // Weather
    temperatureGuide: 'तापमान मार्गदर्शन',
    ideal: 'अधिकांश फसलों के लिए आदर्श। रोपण और क्षेत्र संचालन का सर्वोत्तम समय।',
    increase: 'सिंचाई बढ़ाएँ। फसलों की ताप तनाव के लिए निगरानी करें।',
    critical: 'गंभीर! छाया प्रदान करें, सिंचाई की आवृत्ति बढ़ाएँ।',
    rainfallExpected: 'वर्षा की उम्मीद है',
    rainfallMsg: '2-3 दिनों में मध्यम से भारी वर्षा का पूर्वानुमान है। उचित खेत जल निकासी सुनिश्चित करें। वर्षा से पहले उर्वरक आवेदन पूरा करें। तैयार फसल की कटाई करें।',
    favorableConditions: 'अनुकूल परिस्थितियाँ',
    favorableMsg: 'कृषि संचालन के लिए परिपूर्ण मौसम! तापमान और आर्द्रता आदर्श हैं। रोपण, स्प्रेिंग और सामान्य क्षेत्र कार्य के लिए अच्छा समय।',
    // Additional form and UI strings
    soilLoam: 'दोमट',
    soilSandy: 'बलुई',
    soilSilty: 'गाद वाली',
    soilPeaty: 'पीट वाली',
    soilChalky: 'चॉकी',
    soilDarkBrown: 'गहरा भूरा/काला',
    soilRed: 'लाल',
    soilYellow: 'पीला',
    soilLightBrown: 'हल्का भूरा',
    riskAssessment: 'जोखिम आकलन',
    assessRisk: 'खेती के जोखिम का मूल्यांकन करें',
    riskFactors: 'जोखिम कारक',
    riskFactorWeather: 'मौसम जोखिम',
    riskFactorSoil: 'मिट्टी जोखिम',
    riskFactorDisease: 'रोग जोखिम',
    overall: 'कुल',
    trendAnalysis: 'जोखिम प्रवृत्ति विश्लेषण',
    fertilizerTitle: 'संसाधन अनुकूलन',
    optimizeResources: 'अपनी उर्वरक और सिंचाई अनुकूलित करें',
    currentUsage: 'वर्तमान उपयोग',
    optimizedUsage: 'अनुकूलित उपयोग',
    savings: 'संभावित बचत',
    nitrogenLabel: 'नाइट्रोजन उपयोग',
    phosphorusLabel: 'फॉस्फोरस उपयोग',
    potassiumLabel: 'पोटेशियम उपयोग',
    irrigationWater: 'सिंचाई जल',
    costPerUnit: 'प्रति इकाई लागत',
    estimatedCost: 'अनुमानित लागत',
    optimizationReport: 'अनुकूलन रिपोर्ट',
    scenarioSimulator: 'क्या-अगर परिदृश्य सिम्युलेटर',
    simulateChanges: 'विभिन्न खेत परिस्थितियों का अनुकरण करें',
    scenario: 'परिदृश्य',
    baseline: 'आधारभूत स्तर',
    recommendedChange: 'अनुशंसित परिवर्तन',
    warning: 'चेतावनी',
    minorImpact: 'मामूली प्रभाव',
    yieldComparison: 'पैदावार तुलना',
    factorComparison: 'कारक तुलना',
    simulate: 'अनुकरण करें',
    explainableAI: 'समझाने योग्य एआई',
    understandFactors: 'समझें कि कौन से कारक आपकी पैदावार को प्रभावित करते हैं',
    featureImportance: 'विशेषता महत्व',
    affectsYield: 'आपकी पैदावार को प्रभावित करता है',
    topFactors: 'शीर्ष कारक',
    explanation: 'एआई व्याख्या',
    howItWorks: 'यह कैसे काम करता है',
    analyze: 'विश्लेषण करें',
    predict: 'भविष्यवाणी करें',
    reset: 'रीसेट',
    back: 'पीछे',
    next: 'अगला',
    previous: 'पिछला',
    save: 'सहेजें',
    delete: 'हटाएँ',
    edit: 'संपादित करें',
    view: 'देखें'
  }
};

interface LanguageContextValue {
  lang: SupportedLang;
  setLang: (lang: SupportedLang) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<SupportedLang>(() => {
    const stored = localStorage.getItem('lang') as SupportedLang | null;
    return stored === 'hi' ? 'hi' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = useMemo(() => {
    return (key: keyof typeof translations.en) => {
      const bundle: Dictionary = translations[lang as SupportedLang];
      return bundle[key] ?? translations.en[key] ?? key;
    };
  }, [lang]);

  const setLang = (next: SupportedLang) => setLangState(next);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useI18n() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useI18n must be used within LanguageProvider');
  return ctx;
}
